### PR TITLE
106

### PR DESCRIPTION
**Pull request by umarfarooq95**
implemented Helpline add component but I don't know how to use state dropdown in that component. shall I use the state dropdown component in that

### CODE REVIEW

**Comment by faiyazbits** [comment]
you can use the state dropdown in there . that is why it is a generic component. get state from service and pass it to state dropdown

**Comment by umarfarooq95** [comment]
if i use the state dropdown component there. it throws me a error
Screen Shot 2019-10-02 at 9 41 21 AM

**Comment by faiyazbits** [comment]
let me get back to you on this

**Comment by faiyazbits** [comment]
i have fixed the above error. also created new component called helpline-form.port all the code there.also try to resolve conflicts as mentioned above.push the code and let me know.i will review and merge

**Comment by faiyazbits** [comment]
delete the add-edit component you created

**Comment by umarfarooq95** [comment]
deleted the add-edit component and implement the helpline form component. but it throwing me the same error that I mentioned above when the state dropdown component is used in the form component.

**Comment by umarfarooq95** [comment]
fixed the form field issue

**Pull request merged**
